### ISSUE TITLE
LOGIN - Se muestra un mensaje de error al introducir un usuario incorrecto.

### ISSUE THREAD

**Issue by DianaOviedo4** [1NE0/SistemaGestionAcademica#31]
**Resultado Actual:**
Al intentar ingresar los datos de un usuario (estudiante, director, docente) que no está registrado, se muestra el error ‘ User matching query does not exist’.
**Resultado Esperado:**
Si un usuario no se encuentra registrado, mostrará un mensaje que informe que el usuario que intenta ingresar, no se encuentra.
**Configuración:**
Ambiente: local
user: rosa melano
pass: 1234
**Pasos para reproducir:**
ingresa a la url (ehmm http://127.0.0.1:8000/ por ahora)
ingresar usuario (goku) 
ingresar contraseña (1234)
**Reproducibilidad:**
3/3
**Evidencias:**
![login](https://user-images.githubusercontent.com/37486035/94220529-c6b90400-feae-11ea-8113-ee75c4126d0a.png)

**Comment by 1NE0** [comment]
Ya sale un mensaje de error al intentar ingresar un usuario no registrado
